server.port=8080
spring.application.name=semantico-service

# Microservicios
lexico.service.url=http://localhost:8081
sintactico.service.url=http://localhost:8082

# Ollama
ollama.host=http://localhost:11434/api/generate
ollama.tags-url=http://localhost:11434/api/tags
ollama.model=llama3

# PostgreSQL DataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/sql_automata
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# Ejecutar schema.sql al iniciar
spring.sql.init.mode=always
spring.sql.init.continue-on-error=true
